<footer class="footer">
	<div class="container">
	<p class="col-sm-2"></p>
        <p class="col-sm-4"><a href="https://github.com/amalricBzh/gallicaDownloader" target="_blank">Gallica Downloader</a> v3.1.0 (Melaine/Slim).</p>
	<p class="col-sm-4">&copy; 2017 Maumau. <a href="licence.txt" target="_blank">Licence</a>.</p>
	<p class="col-sm-2"></p>
	</div>
</footer>
</div>
<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
<!-- Bootstrap : Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<!-- Datatables -->
<script type="text/javascript" src="https://cdn.datatables.net/v/bs/dt-1.10.13/datatables.min.js"></script>
<!-- Script principal -->
<script src="/js/gallica.js" type="text/javascript"></script>
</body>
</html>