<!doctype html>
<html lang="fr">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<title>GallicaDownloader V3</title>
    <link rel="icon" href="/favicon.png" type="image/x-icon">
	<!-- Bootstrap : Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Bootstrap : Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- FontAwesome -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <!-- Datatables -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/dt-1.10.13/datatables.min.css"/>
    <!-- Mon Css -->
	<link rel="stylesheet" href="/css/main.css">
</head>

<body role="document">
	<div role="main" class="container theme-showcase">

		<header>
            <div class="container">
			<h1>Gallica Downloader</h1>
			<ul class="menu">
                <li><a href="/"><i class="fa fa-home fa-2x" aria-hidden="true"></i></a></li>
                <li><a href="/projet/nouveau"><i class="fa fa-magic fa-2x" aria-hidden="true"></i></a></li>
            </ul>
            </div>
		</header>
        <?php 
            if (isset($messages['error'])) {
                foreach($messages['error'] as $error) :
            ?>
            <p class="bg-danger"><?= $error ?></p>
            <?php
        endforeach;
            }
            if (isset($messages['succes'])) {
                foreach($messages['succes'] as $succes) :
            ?>
            <p class="bg-success"><?= $succes ?></p>
            <?php
        endforeach;
            }
          
        