<?php include __DIR__ .'/../partials/header.phtml'; ?>
<div class="container">
    <h1>Liste des projets</h1>
    <?php 
    if (count($projets) === 0) {
        echo '<p class="bg-warning">Pas de projets en cours...</p>' ;
    } else {
    ?>
        <table id="projetsTable">
        <thead>
            <tr>
                <th>Identifiant</th>
                <th>Auteur</th>
                <th>Titre</th>
                <th>Nb vues</th>
                <th>{G / <i class="fa fa-download fa-lg"></i> / <i class="fa fa-cloud-upload fa-lg"></i></th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach($projets as $projet): ?>
            <tr>
                <td><a href="<?= $projet['url'] ?>" target="_blank"><?= $projet['id'] ?></a></td>
                <td><div><?= $projet['author'] ?></div></td>
                <td><div><?= $projet['title'] ?></div></td>
                <td><?= $projet['nbVues'] ?></td>
                <td><?= $projet['nbTodo'] ?> / <?= $projet['nbDownloaded'] ?> / <?= $projet['nbGoogleDrive'] ?></td>
                <td>
                    <a href="/projet/nouveau?id=<?= $projet['id'] ?>" class="action" title="Réinitialiser le projet"><i class="fa fa-refresh fa-lg fa-spin-hover"></i></a>
                    <a href="/projet/options?id=<?= $projet['id'] ?>" class="action" title="Modifier les options du projet"><i class="fa fa-cogs fa-lg fa-spin-hover"></i></a>
                    <a href="/download?id=<?= $projet['id'] ?>" class="action" title="Télécharger sur le serveur"><i class="fa fa-download fa-lg"></i></a>
                    <a href="/googleDrive?id=<?= $projet['id'] ?>" class="action" title="Envoyer sur Google Drive"><i class="fa fa-cloud-upload fa-lg"></i></a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
        </table>
        
    <?php } ?>
   
</div>
<?php include __DIR__ . '/../partials/footer.phtml'; ?>
