<?php include __DIR__ .'/../partials/header.phtml'; ?>
<div class="container">
    <h1>Transfert sur GoogleDrive de <?= $projet['id'] ?></h1>
    
    <div id="progressbar"><div class="progress-label">Envoi en cours...</div></div>
    
    <input type="hidden" id="progressbarNbDone" value="<?= $projet['googleDrive']['nb'] ?>">
    <input type="hidden" id="progressbarNbTodo" value="<?= $projet['downloaded']['nb'] ?>">
    
    <p id="resultMessage"></p>
    <div id="temporary-messages" class="col-sm-12"></div>
    <div id="messages" class="col-sm-12"></div>

    <div id="resultats">
        <div id="images"></div>
    </div>

</div>
<script>
    var googleDriveDocumentId = "<?= $projet['id'] ?>";
    var accessToken = "<?= $accessToken ?>";
    var parentFolderId = "<?= $folderId ?>";
</script>
<?php include __DIR__ . '/../partials/footer.phtml'; ?>
