<?php include __DIR__ .'/../partials/header.phtml'; ?>
<div class="container">
    <h1>Transfert sur GoogleDrive de <?= $projet['id'] ?></h1>
    <p>Vues transférées : <span id="nbGoogleDrive"><?= count($projet['googleDrive']) ?></span></p>
    <p>Vues restantes : <span id="nbDownloaded"><?= count($projet['downloaded']) ?></span></p>
    <p id="resultMessage"></p>
    <div id="temporary-messages" class="col-sm-12"></div>
    <div id="messages" class="col-sm-12"></div>

    <div id="resultats">
        <div id="images"></div>
    </div>

</div>
<script>
    var googleDriveDocumentId = "<?= $projet['id'] ?>";
    var accessToken = "<?= $accessToken ?>";
    var parentFolderId = "<?= $folderId ?>";
</script>
<?php include __DIR__ . '/../partials/footer.phtml'; ?>
