<?php include __DIR__ .'/../partials/header.phtml';
$unitesService = new \Service\UnitesService();
if ($projet['downloaded']['nb'] === 0){
    $estimatedSize = '-' ;
    $estimatedTime = '-' ;
} else {
    $estimatedSize = $unitesService->getSize($projet['downloaded']['size'] * $projet['nbVues']/$projet['downloaded']['nb']);
    $estimatedTime = $unitesService->getTime($projet['downloaded']['totalTime'] * $projet['nbVues']/$projet['downloaded']['nb'] - $projet['downloaded']['totalTime']);
}
?>
<div class="container">
    <h1>Téléchargement de <?= $projet['id'] ?></h1>
    
    <div id="progressbar"><div class="progress-label">Chargement en cours...</div></div>
    
    <input type="hidden" id="progressbarNbDone" value="<?= $projet['downloaded']['nb'] ?>">
    <input type="hidden" id="progressbarNbTodo" value="<?= $projet['todo']['nb'] ?>">

    <p>Taille téléchargée : <span id="size"><?= $unitesService->getSize($projet['downloaded']['size']) ?></span></p>
    <p>Taille totale estimée : <span id="estimatedSize"><?= $estimatedSize; ?></span></p>
    <p>Temps passé : <span id="time"><?= $unitesService->getTime($projet['downloaded']['totalTime'] ) ?></span></p>
    <p>Temps restant estimé : <span id="estimatedTime"><?= $estimatedTime; ?></span></p>
    <p id="resultMessage"></p>
    <div id="temporary-messages" class="col-sm-12"></div>
    <div id="messages" class="col-sm-12"></div>

    <div id="resultats">
        <div id="images"></div>
    </div>
   
</div>
<script>
    var documentId = "<?= $projet['id'] ?>";
</script>
<?php include __DIR__ . '/../partials/footer.phtml'; ?>
