<?php include __DIR__ .'/../partials/header.phtml'; ?>
<div class="container">
    <h1>Téléchargement de <?= $projet['id'] ?></h1>
    <p>Vues téléchargées : <span id="nbDownloaded"><?= count($projet['downloaded']) ?></span></p>
    <p>Vues restantes : <span id="nbTodo"><?= count($projet['todo']) ?></span></p>
    <p id="resultMessage"></p>
    <div id="temporary-messages" class="col-sm-12"></div>
    <div id="messages" class="col-sm-12"></div>

    <div id="resultats">
        <div id="images"></div>
    </div>
   
</div>
<script>
    var documentId = "<?= $projet['id'] ?>";
</script>
<?php include __DIR__ . '/../partials/footer.phtml'; ?>
